service: xendit-trial

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  create-notification-type:
    handler: src/controller/notification.createNotificationType
    memorySize: 
    description: Create notification types.
    events:
      - http:
          path: notifications
          method: post

resources: # CloudFormation template syntax from here on.
  Resources:
    notificationsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: notification-table
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi-pk1
            AttributeType: S
          - AttributeName: gsi-sk1
            AttributeType: S
          - AttributeName: gsi-pk2
            AttributeType: S
          - AttributeName: gsi-sk2
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: gsi1
            KeySchema:
              - AttributeName: gsi-pk1
                KeyType: HASH
              - AttributeName: gsi-sk1
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
          - IndexName: gsi2
            KeySchema:
              - AttributeName: gsi-pk2
                KeyType: HASH
              - AttributeName: gsi-sk2
                KeyType: RANGE
            Projection:
              ProjectionType: "ALL"
        BillingMode: PAY_PER_REQUEST
        