name: Deploy master branch

on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: npm install, test
      run: |
        npm install
        npm test
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy --stage prod --region ap-southeast-2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
